#! /bin/bash

# List all the sessions and attach or resurrect any one of them

ZJ_SESSIONS=$(zellij list-sessions --short)
NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

if [ "${NO_SESSIONS}" -ge 2 ]; then
    zellij attach \
    "$(echo "${ZJ_SESSIONS}" | sk)"
else
   zellij attach -c
fi
